# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: U.S. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: production
remotedatabaseurl: "https://gsa.github.io/sdg-data-usa/prod"
# permalink: /news/:year/:month/:day/:title.html

jekyll_get_json:
  - data: meta
    json: 'https://gsa.github.io/sdg-data-usa/prod/meta/all.json'
  - data: headlines
    json: 'https://gsa.github.io/sdg-data-usa/prod/headline/all.json'
  - data: schema
    json: 'https://gsa.github.io/sdg-data-usa/prod/meta/schema.json'
  - data: translations
    json: 'https://gsa.github.io/sdg-translations/translations-0.3.0.json'

analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: mbx.omb.oirasdgs@omb.eop.gov
  suggestions: mbx.omb.oirasdgs@omb.eop.gov
  functional: datagov@gsa.gov
###################################################################################################

# Github Repo for Data
repo_name: sdg-data-usa
branch: develop
org_name: GSA

# Build settings
markdown: kramdown

# Travis Support
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README.md

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: US
  adjective: US

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

# The list of languages that are translated. The first one is the default.
languages:
  - en
  - es
  - fr

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-get-json

remote_theme: open-sdg/open-sdg@0.1.0

custom_css:
  - /assets/css/custom.css
